#!/bin/sh

# Current: /path/to/project/pluk/test
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Parent: /path/to/project/pluk
PLUK_DIR=$(dirname "$SCRIPT_DIR")

# Grandparent: /path/to/project
# This allows 'require("pluk")' to find 'pluk/init.lua'
ROOT_DIR=$(dirname "$PLUK_DIR")

# Run Kakoune
# -n: Don't load the user's kakrc
# -s: Create a named session for our background 'kak -p' to find
# -e: Execute the source command immediately on startup
LUA_PATH="$ROOT_DIR/?.lua;$ROOT_DIR/?/init.lua;;" \
kak -n -s "pluk-test-session" -e "
    source '$SCRIPT_DIR/test.kak'
    buffer *debug*
"

# Clean up test plugins (optional, uncomment if you want to see install location)
rm -rf "$SCRIPT_DIR/plugins"
